package com.old.silence.job.server.domain.model;

import com.baomidou.mybatisplus.annotation.TableName;
import com.old.silence.data.commons.domain.AbstractAutoGeneratedIdAuditable;

import java.math.BigInteger;

/**
 * 号段模式序号ID分配表
 *
 */
@TableName("sj_sequence_alloc")
@Deprecated
public class SequenceAlloc extends AbstractAutoGeneratedIdAuditable<BigInteger> {

    private static final long serialVersionUID = 1L;


    /**
     * 组名称
     */
    private String groupName;

    /**
     * 命名空间ID
     */
    private String namespaceId;

    /**
     * 最大id
     */
    private BigInteger maxId;

    /**
     * 步长
     */
    private Integer step;

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getNamespaceId() {
        return namespaceId;
    }

    public void setNamespaceId(String namespaceId) {
        this.namespaceId = namespaceId;
    }

    public BigInteger getMaxId() {
        return maxId;
    }

    public void setMaxId(BigInteger maxId) {
        this.maxId = maxId;
    }

    public Integer getStep() {
        return step;
    }

    public void setStep(Integer step) {
        this.step = step;
    }
}
